### ISSUE TITLE
Build error on windows

### ISSUE THREAD

**Issue by Mika571** [KinveyApps/Angular2-Starter#1]
Hi, 
When trying to run this sample using `npm start` the npm build command fails to run on my windows machine.
`npm` ERR! Windows_NT 10.0.15063`
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"`
`npm ERR! node v6.10.0`
`npm ERR! npm  v3.10.10`
`npm ERR! code ELIFECYCLE`
`npm ERR! kinvey-angular2-starte@0.0.0 build: `tsc -p src/`
`npm ERR! Exit status 2`

There were only the following warnings when I ran `npm install`
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):`
`npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})`

It seems there is an issue with the typescript compiler?

**Comment by thomasconner** [comment]
We are looking into the issue. Stay tuned...

**Comment by thomasconner** [comment]
We just updated the starter app. Please pull the latest changes and see if this resolves your issue.

**Comment by Mika571** [comment]
Works a treat! You're a legend! Thanks for looking into this.
