### ISSUE TITLE
Can't get the starter app to work.

### ISSUE THREAD

**Issue by Denali7Dev** [KinveyApps/Angular2-Starter#2]
![kinvey-angular2 starter error](https://cloud.githubusercontent.com/assets/19363353/25500528/33981652-2b44-11e7-8f30-995987843f65.png)

I was able to follow the instructions up to the NPM Install. Afterwards, when I run npm start, this is the output I get below. 

A couple background items are that I am more of a Product Manager/UX Designer/Business Analyst vs. Developer. 

Any help is greatly appreciated.

Thanks,

Brandon
______________________________

npm start

> kinvey-angular2-starte@0.0.0 prestart /Users/brandon/Kinvey-Angular2
> npm run build

> kinvey-angular2-starte@0.0.0 build /Users/brandon/Kinvey-Angular2
> tsc -p src/

src/app/components/files.component.ts(16,18): error TS2339: Property 'find' does not exist on type 'typeof Files'.
src/app/components/profile.component.ts(16,22): error TS2339: Property 'data' does not exist on type 'User'.
src/app/components/upload.component.ts(32,20): error TS2339: Property 'upload' does not exist on type 'typeof Files'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! kinvey-angular2-starte@0.0.0 build: `tsc -p src/`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the kinvey-angular2-starte@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2017-04-27T19_11_25_972Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! kinvey-angular2-starte@0.0.0 prestart: `npm run build`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the kinvey-angular2-starte@0.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2017-04-27T19_11_25_998Z-debug.log

**Comment by thomasconner** [comment]
We are working on updating the starter app. Please stand by and I will update you when we have made some changes.

**Comment by thomasconner** [comment]
We just updated the starter app. Please pull the latest changes and see if this resolves your issue.

**Comment by Denali7Dev** [comment]
Thanks Thomas! The changes you made seemed to have resolved the issues.
